// Authored walkthrough examples of the retained subject policies, not model outputs
// or a curriculum. Policy owner: functions/_shared/prompt/subjects/*.ts.
export type Copy = readonly [zh: string, en: string]
export type ShowcaseSubject = 'math' | 'chinese' | 'english'
export type ShowcaseBand = 'lower' | 'upper'
export interface Topic {
  id: string
  subject: ShowcaseSubject
  band: ShowcaseBand
  title: Copy
  question: Copy
  method: Copy
  prompt: Copy
  attempt: Copy
  next: Copy
  concept: string
}
const topic = (id: string, subject: ShowcaseSubject, band: ShowcaseBand, concept: string, title: Copy, question: Copy, method: Copy, prompt: Copy, attempt: Copy, next: Copy): Topic => ({ id, subject, band, concept, title, question, method, prompt, attempt, next })
export const TOPICS: Topic[] = [
  topic('addition', 'math', 'lower', 'make_ten', ['加法与凑十','Addition · making ten'], ['8 + 5，怎样算更方便？','How could you make 8 + 5 easier?'], ['凑十 → 拆分 → 数数辅助','Make ten → split a number → count if stuck'], ['8 再添几个就是 10？','How many more does 8 need to reach 10?'], ['先从 5 里拿出 2。','I can take 2 from the 5.'], ['5 里拿走 2，还剩几个？','After taking 2 from 5, how many are left?']),
  topic('subtraction', 'math', 'lower', 'borrowing', ['减法与退位','Subtraction · regrouping'], ['12 − 5，我减不下去了。','I am stuck on 12 − 5.'], ['借十拆分 → 想加算减 → 倒数辅助','Regroup → use addition to check → count back'], ['先从 12 里拿走 2，还剩几？','Take 2 away from 12 first. What remains?'], ['还剩 10，但只拿走了 2。','10 remains, but I have only taken away 2.'], ['一共要拿走 5，还要拿走几？','You need to take away 5 in all. How many more?']),
  topic('multiplication', 'math', 'lower', 'times_tables', ['乘法与口诀','Multiplication · times tables'], ['4 × 6 的口诀想不起来。','I cannot recall 4 × 6.'], ['拆成熟悉的部分 → 回忆口诀','Split into familiar groups → recall a fact'], ['你记得 4 × 5 的结果吗？','Can you recall 4 × 5?'], ['4 × 5 是 20。','4 × 5 is 20.'], ['从 5 组变 6 组，多了几个 4？','From 5 groups to 6, how many more groups of 4?']),
  topic('comparison', 'math', 'lower', 'compare_size', ['比较与排序','Comparing · ordering'], ['38 和 41，哪个更大？','Which is larger: 38 or 41?'], ['观察数位 → 数轴或画圈比较','Notice place value → compare on a number line'], ['先看十位，各有几个十？','Look at the tens. How many tens in each?'], ['一个有 3 个十，一个有 4 个十。','One has 3 tens and the other has 4 tens.'], ['哪个数在数轴上更靠右？','Which would be farther right on a number line?']),
  topic('distributive', 'math', 'upper', 'round_split', ['计算与分配律','Calculation · distributive property'], ['6 × (10 + 4)，怎样展开？','How do you expand 6 × (10 + 4)?'], ['拆分凑整 → 分步估算 → 逆运算验证','Split into convenient parts → estimate → check'], ['括号里的两项都要参与。你能先把它展开吗？','Both terms in brackets matter. How would you expand it?'], ['先算 6 × 10，再算 6 × 4。','First 6 × 10, then 6 × 4.'], ['这两部分合起来，表示原来的几组？','Together, how many original groups do those parts represent?']),
  topic('word-problem', 'math', 'upper', 'number_line', ['应用题与等量关系','Word problems · relationships'], ['两盒共有 36 支笔，第一盒比第二盒多 6 支。怎样整理条件？','Two boxes hold 36 pens in total. The first has 6 more. How could you organise this?'], ['复述题意 → 线段图或列表 → 找等量关系','Restate → draw a bar model or table → find a relationship'], ['把两盒画成线段，多出的 6 支放在哪？','Draw a bar for each box. Where do the extra 6 go?'], ['第一盒的线段要长一截。','The first bar needs an extra section.'], ['如果只看同样长的部分，总数里要先去掉什么？','To compare equal parts, what needs to come out of the total?']),
  topic('geometry', 'math', 'upper', 'area_split', ['几何与面积拆分','Geometry · splitting area'], ['一块长 8、宽 5 的长方形去掉一个 2 × 2 的角，剩余面积怎么想？','An 8-by-5 rectangle has a 2-by-2 corner removed. How could you find the remaining area?'], ['标注已知 → 找辅助线 → 面积拆分','Label known lengths → add a line → split the area'], ['你能把完整长方形和缺角分别标出来吗？','Can you mark the whole rectangle and the missing corner?'], ['我把它看成大长方形减去小正方形。','I see a large rectangle minus a small square.'], ['先写出完整长方形的面积算式。','Write an expression for the whole rectangle first.']),
  topic('fraction', 'math', 'upper', 'fraction_denom', ['分数与通分','Fractions · common denominators'], ['1/2 和 1/3，能直接比较分子吗？','Can you compare 1/2 and 1/3 just by their numerators?'], ['确认单位一 → 画图 → 通分比较','Identify the same whole → sketch → use a common denominator'], ['同样大的一个整体，分成 2 份和 3 份，每份一样大吗？','If equal wholes are split into 2 or 3 pieces, are the pieces the same size?'], ['不一样，要先分成一样大的小份。','No. I need equal-sized pieces first.'], ['2 和 3 的共同倍数，你能找到一个吗？','Can you find a common multiple of 2 and 3?']),
  topic('equation', 'math', 'upper', 'balance_model', ['方程与倒推','Equations · working backwards'], ['3x + 6 = 21，第一步做什么？','What could you do first with 3x + 6 = 21?'], ['天平模型 → 两边同样操作 → 逆运算验证','Balance model → same operation on both sides → check'], ['左边多了一个 +6。怎样让天平两边仍然平衡？','There is a +6 on the left. How can you keep both sides balanced?'], ['两边都减去 6。','Subtract 6 from both sides.'], ['这样左边剩下什么？','What is left on the left-hand side?']),
  topic('ratio', 'math', 'upper', 'ratio_proportion', ['比例与百分数','Ratios · percentages'], ['果汁和水按 1∶3 混合，水占总量的几分之几？','Juice and water are mixed 1:3. What fraction of the mixture is water?'], ['找单位一 → 画等份 → 比较部分与整体','Identify the whole → draw equal units → compare part and whole'], ['这里的“总量”，包括果汁和水两部分吗？','Does the whole mixture include both juice and water?'], ['包括，要把两种的份数加起来。','Yes, I need to add both sets of units.'], ['你画的全部等份中，水占了几份？','Of all the equal units you drew, how many are water?']),
  topic('pinyin', 'chinese', 'lower', 'initial_finals', ['拼音与声调','Pinyin · tones'], ['“妈”的拼音 mā，怎样拆开读？','How can you break down mā (妈)?'], ['声母韵母拆分 → 声调联想','Separate initial and final → notice the tone'], ['先找声母，你看到了哪个字母？','Find the initial sound first. Which letter do you see?'], ['声母是 m。','The initial is m.'], ['剩下的韵母上，声调符号是什么样？','What does the tone mark on the final look like?']),
  topic('word', 'chinese', 'lower', 'radical_assoc', ['识字与组词','Characters · word formation'], ['用“清”组一个词。','Make a word containing 清.'], ['偏旁联想 → 语境提示 → 有限选择','Use the radical → add context → narrow choices'], ['“清”有三点水。你能想到什么跟水有关的场景？','清 has the water radical. What scene involving water comes to mind?'], ['我想到河里的水。','I am thinking of water in a river.'], ['如果河水不浑浊，你会怎样描述它？','How would you describe river water that is not muddy?']),
  topic('picture', 'chinese', 'lower', 'simple_narrative', ['看图写话','Picture-based writing'], ['设想一幅图：两个孩子在公园种树。你想写些什么？','Imagine two children planting a tree in a park. What would you write?'], ['观察人物动作 → 排顺序 → 自己扩展','Observe people and actions → order events → add your own detail'], ['先说说，他们正在做什么？','Start with what they are doing.' ], ['一个挖土，一个扶着小树。','One digs while the other holds the tree.'], ['你想先写哪个动作？','Which action would you write about first?']),
  topic('reading-zh', 'chinese', 'upper', 'key_sentence', ['阅读理解','Reading comprehension'], ['短文：“雨停了。小林收起伞，跑向操场。”小林为什么收伞？','Text: “The rain stopped. Xiaolin put away the umbrella and ran to the playground.” Why put it away?'], ['定位段落 → 找关键句 → 用自己的话复述','Locate the passage → find evidence → retell'], ['问题问的是原因。原文里哪个变化可能与它有关？','The question asks for a reason. Which change in the text might explain it?'], ['前一句说雨停了。','The previous sentence says the rain stopped.'], ['把这条线索和收伞连起来，用自己的话说一遍。','Connect that clue to the umbrella in your own words.']),
  topic('sentence', 'chinese', 'upper', 'grammar_error', ['造句与病句','Sentences · editing'], ['“我看到了美丽的风景和悦耳的歌声。”读起来哪里不合适？','“I saw a beautiful view and a lovely song.” What does not fit?'], ['朗读检查 → 分析成分 → 自己修改','Read aloud → inspect sentence parts → revise'], ['“看到”能同时搭配后面的两样事物吗？','Can “saw” describe both things that follow it?'], ['歌声应该用耳朵听。','A song is something I hear.'], ['保留原意，你会怎样改这句话？','How would you revise it while keeping the meaning?']),
  topic('writing', 'chinese', 'upper', 'essay_outline', ['作文构思','Planning a composition'], ['写一次你帮助别人的经历，从哪里开始？','How would you start a story about helping someone?'], ['开头—中间—结尾 → 分段提问 → 学生表达','Opening–middle–ending → questions for each → learner writes'], ['你想写哪一次具体的经历？','Which specific experience would you choose?'], ['我想写帮同学找水杯。','I want to write about helping a classmate find a bottle.'], ['事情开始时，发生了什么？','What happened at the beginning?']),
  topic('classical', 'chinese', 'upper', 'char_meaning', ['文言文与字义','Classical Chinese · meaning'], ['“学而时习之”里的“习”，可以怎样理解？','How could you understand 习 in 学而时习之?'], ['字面义 → 引申义 → 联系现代用法','Literal meaning → extended meaning → modern usage'], ['现代词语“练习”里，你会做什么动作？','What do you do when you “practise” (练习)?'], ['把学过的再做一遍。','Try what I have learned again.'], ['把这个意思放回原句，读起来通顺吗？','Does that meaning fit when you put it back into the sentence?']),
  topic('phonics', 'english', 'lower', 'phonics', ['自然拼读与拼写','Phonics · spelling'], ['cat 这个词，可以听出哪些声音？','Which sounds can you hear in cat?'], ['自然拼读分解 → 音节拆分','Separate sounds → split syllables'], ['先听开头的声音，像哪个字母的发音？','Listen to the first sound. Which letter does it sound like?'], ['开头像 c 的声音。','The beginning sounds like c.'], ['接下来，你听到了什么声音？','What sound can you hear next?']),
  topic('letters', 'english', 'lower', 'abc_sounds', ['字母书写','Writing letters'], ['小写 b 和 d 容易写反，怎样观察？','How could you distinguish lowercase b and d?'], ['观察形状 → 笔顺引导 → 自己书写','Observe the shape → trace the strokes → write'], ['先看 b，竖线在圆圈的哪一边？','Look at b. Which side of the circle is the upright stroke on?'], ['在左边。','On the left.'], ['你在纸上写一个 b，再对照看看。','Write a b on paper, then compare it.']),
  topic('question', 'english', 'lower', 'simple_dialogue', ['简单问答','Simple questions'], ['“What color is the apple?” 这句话在问什么？','What is “What color is the apple?” asking about?'], ['定位关键词 → 理解问句 → 模板引导','Find the key words → understand → use a pattern'], ['先看 what color，它问颜色还是数量？','Does “what color” ask about colour or quantity?'], ['问颜色。','Colour.'], ['那你会先观察苹果的哪个特点？','Which feature of the apple would you look at first?']),
  topic('grammar', 'english', 'upper', 'sentence_parts', ['语法选择','Grammar choices'], ['He ___ to school every day.（go / goes）','He ___ to school every day. (go / goes)'], ['识别成分 → 提示规则 → 学生应用','Identify sentence parts → explain rule → learner applies'], ['先找主语：这里是谁去学校？','Find the subject first. Who goes to school?'], ['主语是 he。','The subject is he.'], ['一般现在时的第三人称单数，动词常加 s。这里怎样用这条规则？','In the simple present, third-person singular verbs usually add s. How would you apply that?']),
  topic('reading-en', 'english', 'upper', 'reading_strategy', ['阅读与词汇','Reading · vocabulary'], ['“Mia packed an umbrella because the sky was dark.” Why did Mia pack it?','“Mia packed an umbrella because the sky was dark.” Why did Mia pack it?'], ['定位段落 → 关键句 → 词汇辅助','Locate → find the key sentence → support vocabulary'], ['题目问原因，句子里哪个词引出了原因？','Which word in the sentence introduces a reason?'], ['because 后面是原因。','The reason comes after because.'], ['用自己的话说说，这条线索和雨伞有什么关系？','In your own words, how does that clue relate to the umbrella?']),
  topic('cloze', 'english', 'upper', 'context_infer', ['完形填空','Cloze exercises'], ['“It was cold, so Tom put on his ___.”（coat / shorts）','“It was cold, so Tom put on his ___.” (coat / shorts)'], ['上下文线索 → 语法检查 → 排除','Read context → check grammar → eliminate'], ['先找描述天气的词，是哪一个？','Which word tells you about the weather?'], ['是 cold。','Cold.'], ['两种衣服里，哪一种更适合这个天气？','Which of the two items of clothing fits that weather?']),
  topic('translation', 'english', 'upper', 'grammar_struct', ['句子翻译','Sentence translation'], ['把“我每天读书”翻译成英语，先处理什么？','How would you begin translating 我每天读书 into English?'], ['关键词 → 句子结构 → 逐块翻译','Find key words → identify structure → translate in parts'], ['先找动作，这句话里做了什么？','Find the action first. What is being done?'], ['动作是读书。','The action is reading.'], ['你会用哪个英语动词表示这个动作？','Which English verb would express that action?']),
]


export const KNOWLEDGE_EN: Record<string, string> = {
  make_ten: 'Making ten', split_method: 'Splitting numbers', counting: 'Counting', long_form: 'Column arithmetic', diagram: 'Drawing a model', carrying: 'Addition with carrying', borrowing: 'Subtraction with regrouping', times_tables: 'Times tables', reverse_reasoning: 'Working backwards', compare_size: 'Comparing numbers', place_value: 'Place value', simple_fraction: 'Simple fractions',
  round_split: 'Splitting into round numbers', step_estimate: 'Stepwise estimation', inverse_check: 'Checking with inverse operations', number_line: 'Bar models', table_method: 'Organising a table', auxiliary_line: 'Auxiliary lines', area_split: 'Splitting area', fraction_denom: 'Common denominators', balance_model: 'Balance model', equation_reverse: 'Reversing an equation', ratio_proportion: 'Ratio relationships', volume_area: 'Volume and area', divisibility: 'Divisibility and remainders',
  initial_finals: 'Pinyin initials and finals', radical_assoc: 'Character radicals', guided_observe: 'Observing before writing', stroke_order: 'Stroke order', word_context: 'Word combinations', rhyme_tone: 'Finals and tones', sentence_sense: 'Sentence sense', read_aloud: 'Reading aloud', punctuation_use: 'Punctuation', simple_narrative: 'Simple narrative structure', para_locate: 'Locating a paragraph', key_sentence: 'Finding key sentences', retell_train: 'Retelling', grammar_error: 'Editing sentences', essay_outline: 'Composition outlines', metaphor_figure: 'Figures of speech', theme_extract: 'Identifying a theme', inference: 'Inferring meaning', ancient_poetry: 'Classical poetry', char_meaning: 'Word and character meanings', reading_comp: 'Comprehension strategies', writing_express: 'Written expression', idiom_usage: 'Using idioms',
  phonics: 'Phonics', syllable_split: 'Splitting syllables', sight_words: 'Sight words', basic_sentence: 'Basic sentence patterns', abc_sounds: 'Letter sounds', simple_dialogue: 'Simple dialogue', number_words: 'Number words', daily_vocab: 'Everyday vocabulary', yes_no_question: 'Yes/no questions', sentence_parts: 'Sentence parts', context_infer: 'Meaning from context', word_root: 'Word roots', tense_use: 'Verb tenses', reading_strategy: 'Reading strategies', grammar_struct: 'Grammatical structure', writing_organize: 'Organising writing', passive_voice: 'Passive voice', clause_complex: 'Clause structure', preposition_use: 'Prepositions', phrase_colloc: 'Phrase collocations', listening_comp: 'Listening comprehension',
}
